name: xtbML
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - blas=1.0=mkl
  - ca-certificates=2021.10.8=ha878542_0
  - cudatoolkit=10.2.89=h8f6ccaa_10
  - intel-openmp=2022.0.1=h06a4308_3633
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=11.2.0=h1d223b6_12
  - libgomp=11.2.0=h1d223b6_12
  - libnsl=2.0.0=h7f98852_0
  - libstdcxx-ng=11.2.0=he4da1e4_12
  - libuv=1.43.0=h7f98852_0
  - libzlib=1.2.11=h36c2ea0_1013
  - mkl=2022.0.1=h06a4308_117
  - ncurses=6.3=h9c3ff4c_0
  - openssl=3.0.0=h7f98852_2
  - pip=22.0.3=pyhd8ed1ab_0
  - python=3.8.12=h0744224_3_cpython
  - python_abi=3.8=2_cp38
  - pytorch=1.10.2=py3.8_cuda10.2_cudnn7.6.5_0
  - pytorch-mutex=1.0=cuda
  - readline=8.1=h46c0cb4_0
  - setuptools=60.9.2=py38h578d9bd_0
  - sqlite=3.37.0=h9cd32fc_0
  - tk=8.6.12=h27826a3_0
  - typing_extensions=4.1.1=pyha770c72_0
  - wheel=0.37.1=pyhd8ed1ab_0
  - xz=5.2.5=h516909a_1
  - zlib=1.2.11=h36c2ea0_1013
  - tomli
  - pydantic
  - pip:
      - tad-dftd3
